### ISSUE TITLE
Issue with server.query()

### ISSUE THREAD

**Issue by ph3onixleader** [Dinnerbone/mcstatus#113]
I am coding a private discord bot for me and my friends and I have been having issues with it as everything works fine until I hit my command that sends the info about players and I was wondering if there was any solution to it. If u need code i can provide it when I'm free!(side note:I am using repl so that my friend doesn't have to run it on his pc)

**Comment by Iapetus-11** [comment]
The code would be nice to see what you're doing! Also the command being used would be good too!

**Comment by kevinkjt2000** [comment]
In order for us to help you, you'll have to start by providing something that we can help with... The code that is causing your issue would be a good start. Keep in mind that we aren't here to help with the discord library that you might be struggling with; you will have to show why your code is failing with server.query(). Honestly, my first guess is that there is probably a firewall issue #72, but it's just that... a guess... Because you haven't shared any error messages or context! Help us to help you!

[How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)

**Comment by ph3onixleader** [comment]
import discord
import os
from replit import db
from KEEP_ALIVE import KEEP_ALIVE
from mcstatus import MinecraftServer

client = discord.Client()

@client.event 
async def on_ready():
  print("Pilot {0.user} is ready for battle".format(client))

server = MinecraftServer.lookup("no")


@client.event
async def on_message(message):
  if message.author == client.user:
    return

  if message.content.startswith(">server"):
    status = server.status()
    await message.channel.send("The server has {0} players and replied in {1} ms".format(status.players.online, status.latency))

  if message.content.startswith(">ping"):
    latency = server.ping()
    await message.channel.send("The server replied in {0} ms".format(latency))

  if message.content.startswith(">help"):
    await message.channel.send("you can use these commands:?help, ?ping, ?players, ?server side note:things may not work 100% so dont expect it to be 10/10 quality")  

  if message.content.startswith(">players"):
    query = server.query()
    await message.channel.startswith("The server has the following players online: {0}".format(", ".join(query.players.names)))




KEEP_ALIVE()
client.run(os.getenv("TOKEN"))

if there is anything else you need then just ask (apologise for not posting code before)

**Comment by kevinkjt2000** [comment]
I guessed it right; see #72. There's a network/firewall issue preventing access to the query port.
