### ISSUE TITLE
Add more Features/apis

### ISSUE THREAD

**Issue by HydroGames-dev** [Dinnerbone/mcstatus#127]
Hi, can you add more Features / APIs
Like:
Whitelist: on/off
Server: Online/Offline
Minecraft Events For both java and bedrock
Rcon support

**Comment by kevinkjt2000** [comment]
No, and please go read http://www.catb.org/~esr/faqs/smart-questions.html before ever posting here again. It's clear that you did not put a whole lot of thought into this request of yours.

**Comment by ItsiAdam** [comment]
> No, and please go read http://www.catb.org/~esr/faqs/smart-questions.html before ever posting here again. It's clear that you did not put a whole lot of thought into this request of yours.

You are a moron

**Comment by ItsiAdam** [comment]
dinnerbone egomaniac

**Comment by kevinkjt2000** [comment]
> dinnerbone egomaniac

@ItsiAdam Fine, I'll take the bait and waste my time explaining this more than I probably should. I deleted your last comment because it was blatantly not constructive in any way. Again, here you are without anything constructive to add to this issue. I am not dinnerbone, so why did you have to mention his username in this latest comment of yours?

The OP clearly did not put a lot of thought into their issue.

> Whitelist: on/off

This is a status library. It's a read-only check to poll some public information from the server. The OP seriously misunderstood the purpose of mcstatus to ask for such a feature.

> Server: Online/Offline

This is something that mcstatus can already do... If the server responds, it's online; if it doesn't, it's offline... An idea with no research behind it.

> Minecraft Events For both java and bedrock

Events? Huh? What do they mean? What events is the OP talking about? This is the main asking point that led me to post a link to [_How To Ask Questions The Smart Way_](http://www.catb.org/~esr/faqs/smart-questions.html). I would be actually curious about this if the OP would produce some effort in the form of a smart question that showed a modicum of research, but as I've already pointed out they have both misunderstood the purpose of the library and what it is already capable of. This leads me to wonder if they even know about recent additions to the library that add support for Bedrock status (e.g. #103)

> Rcon support

Obviously, any rcon library would be an answer to this desire. Why should mcstatus bundle rcon with it when we are a read-only status library that simulates the Minecraft client protocols? Again, no understanding of what mcstatus is by asking for this feature.

Additionally, what would they like these features to look like? Code samples? How would these features be invoked? Does it need to be a new part of the CLI tool too? How would they want that to look? Clearly, no research applied for this.

So, respectfully, if you have nothing constructive to add, then shut up so the rest of us don't have to read your petty squabbling. Perhaps you would also benefit from reading that catb article.

![image](https://imgs.xkcd.com/comics/free_speech_2x.png)

**Comment by ItsiAdam** [comment]
hi

**Comment by ItsiAdam** [comment]
oops sorry, one sec

**Comment by ItsiAdam** [comment]
can you add whitelist on/off and server online/offline mode please
