### ISSUE TITLE
Is there away to get tps (ticks per second)

### ISSUE THREAD

**Issue by PizzaRules668** [Dinnerbone/mcstatus#137]
Im trying to see if there is a why get get tps of the server. Is there a way to get that?

**Comment by Iapetus-11** [comment]
Ticks per second would either have to be via RCON if there's a command for it, or via a plugin. There's no way to get TPS (that I know of) via the status protocols which is all that this library supports.

**Comment by kevinkjt2000** [comment]
The protocol does support fetching server tick age https://wiki.vg/Protocol#Time_Update

I feel it would be too much for this library to fetch the server's tick age twice to compute the TPS. The status protocol is initiated on the handshake instead of the login protocol (which would be required to get the server's tick age). I don't see simulating a player long enough to receive multiple time updates as a feasible solution; I could be proven wrong on this because I have no experience with implementing my own Minecraft client. I'd also rather avoid handling authentication/login and keep mcstatus simple in that regard.

RCON is a possibility too, and I feel that would be better suited to an actual RCON library which mcstatus is not.

If there is a way to fetch TPS from a plugin without authenticating, I'm open to any PRs that accomplish that as long as existing vanilla behavior continues to function. I'll leave this open as a possible feature request in case someone has an idea that could retrieve this status without authenticating.

**Comment by CoolCat467** [comment]
Have a plugin that modifies json sent in the status request packet to add an extra field with TPS in it. Not sure how you'd calculate that server side, but I'm sure it's possible. It would force the server to have such a plugin for use though.
