### ISSUE TITLE
website alternative?

### ISSUE THREAD

**Issue by Aaronstar-McClure** [Dinnerbone/mcstatus#157]
so i see that dinnerbone's page is down because of a recapatcha issue. is anyone hosting a mirror or alternative web page?

**Comment by kevinkjt2000** [comment]
Not that I'm aware of.

**Comment by kevinkjt2000** [comment]
I'm looking at possibly using Brython to deploy a GitHub pages (or some other static site host) version of mcstatus. This would alleviate the need for running a server as a backend by running Python code directly in the web browser of the visitor. The issue is that not all Python code is supported, such as asyncio. Instead, there are other built-in async functions that are mostly identical, so this may be tricky to do. The cost of running a backend server and the time involved to set one up in a serverless environment has deterred me thus far, so Brython seems promising and therefore possibly worth the effort. No ETA on when I'll have something working, but I am tinkering with this.
