### ISSUE TITLE
BungeeCord support?

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#174]
#92 and #112 bring up an issue regarding BungeeCord. From mcstatus' perspective there's a lack of network connection because the responses never return and instead are captured on BungeeCord's end by something. What is that something? Could be a firewall, could be a custom implementation of Minecraft, could be something else?

mcstatus has Bedrock and standard Java edition protocols supported. I'm open to another if BungeeCord is different. In that case, this would be a "feature request". If there's an issue on BungeeCord's end, then this is a "won't fix".

**Comment by alexitx** [comment]
I searched around and by the looks of things BungeeCord does this by design:
- https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L283
- https://github.com/WaterfallMC/Waterfall-Old/issues/23#issuecomment-179324921 (fork of BungeeCord)

To the best of my knowledge the client is first expected to request status and then ping. I'm not sure if that should be the correct behaivour though since Velocity and all server platforms I've tested respond to just ping, but it doesn't look like a 'bug' on BungeeCord's end either.

So I think mcstatus technically works correctly, the user just needs to always request the status from BungeeCord proxies. Though I'm not against an implementation that can request only pings from BungeeCord if that's possible.
