### ISSUE TITLE
will not install for python 3.10+

### ISSUE THREAD

**Issue by badgeminer** [Dinnerbone/mcstatus#175]
will not install for python 3.10+

**Comment by Iapetus-11** [comment]
How so? Send any errors or messages that occur when it fails installing, so we can fix or troubleshoot the issue.

**Comment by kevinkjt2000** [comment]
Actually I'm gonna change this to Bug, because it's intentional that python 3.10 is not supported.

https://github.com/Dinnerbone/mcstatus/blob/a31e808b1f35190c3875645e40d5bc31a6f3a950/pyproject.toml#L32
because of a development dependency pytype https://github.com/Dinnerbone/mcstatus/blob/a31e808b1f35190c3875645e40d5bc31a6f3a950/poetry.lock#L489

I'll cut a release later that fixes this by only installing pytype if python is less than 3.10

There could be other dependencies that are gated on python 3.10 too, but pytype was the only one that I found quickly.

**Comment by kevinkjt2000** [comment]
I'm fighting a test that's failing before I can release the change I'm making that fixes this.

**Comment by kevinkjt2000** [comment]
Fixed in v8.0.0 with (27fbe2e)
