### ISSUE TITLE
Unable to use module in a python script

### ISSUE THREAD

**Issue by KarsonTheFoxx** [Dinnerbone/mcstatus#221]
I just installed mcstatus onto my machine after a few months of unuse, however when i attempt to use the modules i get different errors depending on where i run the file, from the terminal i get a "no module named mcstatus" and in VS code i get an "Import error" saying that there is a circular import somewhere although all i have is `from mcstatus import MinecraftServer` stranger yet vscode recognises the module and still gives prompts, im using v8.0.0 of the module with python 3.7, im running this in buster 10

**Comment by ItsDrike** [comment]
You probably named your python package (folder) `mcstatus`, and you're importing it from inside of itself, hence the circular import.

As for the issue of no module named mcstatus, I don't know, you're probably running a different python version in your terminal, perhaps you only installed in a virtual environment, or in a different python version?

Also, this repository is deprecated and replaced by https://github.com/py-mine/mcstatus (as can be seen from the readme), please use that if you have any further questions.

**Comment by KarsonTheFoxx** [comment]
> You probably named your python package (folder) `mcstatus`, and you're importing it from inside of itself, hence the circular import.
> 
> As for the issue of no module named mcstatus, I don't know, you're probably running a different python version in your terminal, perhaps you only installed in a virtual environment, or in a different python version?
> 
> Also, this repository is deprecated and replaced by https://github.com/py-mine/mcstatus (as can be seen from the readme), please use that if you have any further questions.

alright, however i havent changed my python packages name, and i have no clue how to launch a vm, VScode runs off the most recent update i can install imn vs code, thanks for telling me it moved

**Comment by ItsDrike** [comment]
python package is the same, the new repository is a continuation of this one, it just needed a new place because Dinnerbone isn't a person who's easy to get a hold of and we needed to move this repository into an organization, where we could better fine-tune who has write/triage/... permissions, add webhooks, protected branch rules, etc.

And again, if you still have issues, please open an issue there, don't continue this thread. Alternatively, you can also hop on our discord server (link is in the new repo's readme) and get help there.

**Comment by blackbeareatsfish** [comment]
@ItsDrike Since this repository is deprecated in favour of https://github.com/py-mine/mcstatus:
1. Would it make more sense to archive this repository with only read access (like this one: https://github.com/asottile-archive/future-fstrings)?
2. Would it be okay to close this issue?
3. How about removing it from CodeTriage altogether if triaging for this particular repository is no longer required?

**Comment by kevinkjt2000** [comment]
Closing and locking. Please take any necessary activity to the new repo.
