### ISSUE TITLE
status.description confusing

### ISSUE THREAD

**Issue by averysumner** [Dinnerbone/mcstatus#47]
Change status.description to status.motd, it is very confusing

**Comment by kevinkjt2000** [comment]
It is called `description` because that is what the protocol used to communicate with a minecraft server calls it.  See [this page](https://wiki.vg/Server_List_Ping).  The response packet includes:

```
...
    "description": {
        "text": "Hello world"
    },
...
```

I'm going to go ahead and close this given that mcstatus is heavily in the realm of using the same names as the protocol does.
