### ISSUE TITLE
recaptcha on dinnerbone serverstatus site not showing up

### ISSUE THREAD

**Issue by DoomSquirter** [Dinnerbone/mcstatus#63]
didn't know where else to put this.  

got hit with a recaptcha on https://dinnerbone.com/minecraft/tools/status/

tried three different browsers (edge, firefox, pale moon), firefox/edge with no addons.  

I get a recaptcha section to prove I'm not a human but no captcha shows up.  I see that as of march 31st, 2018, api v1 of recaptcha is no longer working.  wondering if this is the reason?
https://developers.google.com/recaptcha/docs/faq

**Comment by MarkL4YG** [comment]
> I see that as of march 31st, 2018, api v1 of recaptcha is no longer working.

Yes, that is the reason.  
Sadly I've got to tell you not to expect any sort of answer from anyone able to resolve that issue as this repository seems to be out of maintenance since years.  
If @Dinnerbone would just allow collaborators. But hey, in contrast to Mojang he uploaded his source code to allow 3rd party access to fixes and modifications so feel free to build your own website for checking a servers status.

**Comment by kevinkjt2000** [comment]
There is a collaborator here now :)
And PRs are definitely welcome.

**Comment by kevinkjt2000** [comment]
Ummmm there isn't any website code on this repo. This issue belongs elsewhere. Perhaps try reaching out to dinnerbone directly on his twitter account next time?
