### ISSUE TITLE
ReferenceError: Recaptcha is not defined (site shows nothing)

### ISSUE THREAD

**Issue by EthanHermsey** [Dinnerbone/mcstatus#67]
Heya,

In chrome and firefox, I get the following error in the console. and all elements on the page disappear. I can't run the query check.

recaptcha_ajax.js:1 Failed to load resource: the server responded with a status of 404 ()
angular-recaptcha.min.js:7 Uncaught ReferenceError: Recaptcha is not defined
    at angular-recaptcha.min.js:7
angular.js:10573 Error: [$injector:unpr] http://errors.angularjs.org/1.3.0-rc.0/$injector/unpr?p0=vcRecaptchaServiceProvider%20%3C-%20vcRecaptchaService
    at angular.js:38
    at angular.js:3925
    at Object.d [as get] (angular.js:4058)
    at angular.js:3930
    at d (angular.js:4058)
    at Object.e [as invoke] (angular.js:4090)
    at B.instance (angular.js:7712)
    at angular.js:6991
    at r (angular.js:340)
    at A (angular.js:6990)

**Comment by MarkL4YG** [comment]
Hey there,  :wave: 
while this repository is maintained again since a few weeks, I don't think that counts for Dinnerbone's website which is just a website he built to show that the library is working.  
The library itself is written in Python so you can integrate it into your own web application if you want to.  
I don't think that trying to reach out to @Dinnerbone for a fix is worth the time for such a simple site as he appears to be very busy and therefore, absent.

**Comment by kevinkjt2000** [comment]
@EthanHermsey This repo does not contain any website code.  Please reach out to the owner of that website instead.

**Comment by EthanHermsey** [comment]
I thought the owner of dinnerbone.com would be dinnerbone.
I assumed this was a legitimate minecraft tool and this was the repo for it. 
Sorry I misjudged, just trying to help.

**Comment by MarkL4YG** [comment]
He is and it is but the webseite of Dinnerbone is no longer maintained, just as many of his projects.

Mcstatus is maintained again as Dinnerbone kindly provided access rights to @kevinkjt2000 :)

**Comment by kevinkjt2000** [comment]
No need to apologize :)

Since this isn't the first time someone has opened up this specific issue,
I sent a Twitter direct message to Dinnerbone about it.  But I'm not sure
if he'll respond or not.

If this continues, I may change the new issue template to reflect that this
repo has none of Dinnerbone's personal website code.
