### ISSUE TITLE
How can the script tell if the server is offline?

### ISSUE THREAD

**Issue by TheLittleDoc** [Dinnerbone/mcstatus#79]
Hi there,
I've been building a Discord bot on Python that checks my personal minecraft server for activity. When the server is up, that's not a problem, but when the server is down and someone messages at it, it doesn't print anything out. Is there a value that I can use to determine directly if the server is up or not? I'm fairly new to Python, so I'm sure there's a more efficient way to do this, but I've attached my code below (of course with token and IP elsewhere). Please let me know how I might do this. Any and all help is greatly appreciated! 

Thanks,
Doc

```
import os
import random
import sched, time

import discord
from dotenv import load_dotenv
from mcstatus import MinecraftServer

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

client = discord.Client()

s = sched.scheduler(time.time, time.sleep)

@client.event
async def on_ready():
    print(f'{client.user.name} has connected to Discord!')

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content == 'Server status?':
        server = MinecraftServer("lol you can't have my ip", 25565)
        status = server.status()
        print(status.latency)
        if status.latency > 20:
                response = "The server has {0} players and replied in {1} ms".format(status.players.online, status.latency)
                await message.channel.send(response)
//        elif status.latency == ??:
//                response = "The server is offline."
//                await message.channel.send(response)
// This is the section above I'm having issues with

client.run(TOKEN)
```

**Comment by kevinkjt2000** [comment]
One of `socket.timeout`, `gaierror`, or `ConnectionRefusedError` is raised when the server is unreachable.

Luckily for you I have some experience with using what looks to be discord.py in your post. You are missing an exception handler. In the past I had this code when I worked with that library (you'll need to modify this to fit your needs and possibly update it as this code is over 2 years old):

```python
        async def on_command_error(self, exception, context):
            original = exception.original.__class__.__name__
            if original == 'ConnectionRefusedError' or original == 'timeout':
                await self.bot.send_message(
                    context.message.channel,
                    'The server is not accepting connections at this time.',
                )
            elif original == 'gaierror':
                await self.bot.send_message(
                    context.message.channel,
                    'The !ip is unreachable; complain to someone in charge.',
                )
```

It is by design that python libraries should raise exceptions in exceptional cases such as this. I'm 99% certain that if you add an exception handler to your discord client that you will see the error mcstatus raises. Let me know if you see the exception after adding your own error handler code.

**Comment by TheLittleDoc** [comment]
Thanks! Really big help!

Thanks,
Doc
